name: Build and Publish on PR Push and main commit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish OnlineMediaShelf.Web --configuration Release --no-restore --output ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-project
          path: ./output
