name: Tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Ensure this matches your project’s .NET version

      - name: Install GitVersion tool
        run: dotnet tool restore
          
      - name: Run GitVersion
        run: |
          echo "TAG_NAME=$(dotnet gitversion /showvariable MajorMinorPatch)" >> $GITHUB_OUTPUT
        id: version

      - name: Create release tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release/${{ steps.version.outputs.TAG_NAME}}',
              sha: context.sha
            })

      - name: Create version tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.version.outputs.TAG_NAME}}',
              sha: context.sha
            })
